export { default as Navbar } from './Navbar/Navbar'
export { default as Home } from './Home/Home'
export { default as About } from './About/About'
export { default as Skills } from './Skills/Skills'
export { default as Works } from './Works/Works'
export { default as Contact } from './Contact/Contact'